CREATE SEQUENCE "USER_SEQ" AS INTEGER START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 NO CYCLE NO CACHE;
CREATE SEQUENCE "CHECKLIST_SEQ" AS INTEGER START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 NO CYCLE NO CACHE;

CREATE TABLE USER (
	USER_ID INTEGER NOT NULL,
 	USERNAME   VARCHAR(30) NOT NULL,
  USER_ROLE   VARCHAR(10) NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE CHECKLIST (
	CHECKLIST_ID INTEGER NOT NULL,
 	ITEM_NAME   VARCHAR(30) NOT NULL,
 	ITEM_DESC VARCHAR(75) NOT NULL,
  CHECKED   BOOLEAN NOT NULL,
  PRIMARY KEY (CHECKLIST_ID)
);
