-- insert user content --

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'testuser', 'user') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'emily.doran1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'brendan.bartow1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'christopher.crawley1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'abel.simon1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'thomas.burda1', 'admin') ;

-- insert checklist content --

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME,  ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'courseDes', 'Course Description', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'courseObj', 'Course Objectives', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'courseCred', 'Credits Allocated to Course', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'preReq', 'Prerequisites', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'gradeDet', 'Basis of Grade Determination', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'otherpolicies', 'Other Course Policies', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
     VALUES (CHECKLIST_SEQ.NEXTVAL, 'instrName', 'Instructor''s Name', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'instrContact', 'Instructor Contact Information', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'assesMethod', 'Method of Assessment', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'rubrics', 'Rubrics at Course and Project Levels', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'biblio',  'Bibliographic Resources', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'assignments', 'Assignments', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'taskCrit', 'Demonstrate That the Course Meets Time on Task Criteria', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'courseNum', 'Course Number Must be Designated as L/N', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'format', 'Classroom Format', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'attenPol', 'Attendance Policy', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'reqRead', 'Semester Required Reading', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'acadHonest', 'Statement on Academic Honesty', false) ;


INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'teachAct', 'TEACH Act Disclosure', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'accommod', 'Accommodations & Assesibilty Statement', false) ;

INSERT INTO CHECKLIST (CHECKLIST_ID, ITEM_NAME, ITEM_DESC, CHECKED)
    VALUES (CHECKLIST_SEQ.NEXTVAL, 'diversity', 'Statement on Diversity', false) ;
