INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'testuser', 'user') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'emily.doran1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'brendan.bartow1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'christopher.crawley1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'abel.simon1', 'admin') ;

INSERT INTO USER (USER_ID, USERNAME, USER_ROLE)
    VALUES (USER_SEQ.NEXTVAL, 'thomas.burda1', 'admin') ;
